version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: 192.168.1.174
      KAFKA_ADVERTISED_HOST_NAME: 192.168.50.51
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_LOG_RETENTION_BYTES: -1
      KAFKA_LOG_RETENTION_HOURS: -1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  cache:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
  importer:
    build:
      context: .
      dockerfile: ./services/importer/Dockerfile
    environment:
      - KAFKA_HOST=kafka
      - REDIS_HOST=cache
    env_file:
      - services/importer/.env
    depends_on:
      - kafka
      - cache